{{- range .Values.stores }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  selector:
    app: {{ .name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .containerPort | default 80 }}
---
{{- end }}

